import { Hono } from 'hono';

// Env is generated by `wrangler types` (worker-configuration.d.ts) from
// wrangler.jsonc vars + .dev.vars secrets — never hand-written.
const app = new Hono<{ Bindings: Env }>();

app.onError((err, c) => {
  console.error(
    JSON.stringify({
      message: 'unhandled error',
      path: c.req.path,
      error: err instanceof Error ? err.message : String(err),
    })
  );
  return c.json({ error: 'Internal server error' }, 500);
});

app.get('/health', (c) => c.json({ ok: true, service: 'farmsquare-api' }));

// WooCommerce REST v3 proxy. The consumer key/secret live only in Worker
// secrets, never in the app bundle.
// TODO: verify a Firebase ID token (Authorization header, jose + Google JWKS)
// before allowing non-GET methods once WC write keys are provisioned.
app.all('/wc/*', async (c) => {
  const path = c.req.path.replace(/^\/wc/, '');
  const target = new URL(`${c.env.WC_URL}/wp-json/wc/v3${path}`);

  const incoming = new URL(c.req.url);
  incoming.searchParams.forEach((value, key) => {
    // Never trust client-sent credentials.
    if (key === 'consumer_key' || key === 'consumer_secret') return;
    target.searchParams.append(key, value);
  });
  target.searchParams.set('consumer_key', c.env.WC_KEY);
  target.searchParams.set('consumer_secret', c.env.WC_SECRET);

  const init: RequestInit = {
    method: c.req.method,
    headers: { accept: 'application/json', 'content-type': 'application/json' },
  };
  if (c.req.method !== 'GET' && c.req.method !== 'HEAD') {
    // Order payloads are small, bounded JSON — safe to buffer.
    init.body = await c.req.text();
  }

  const res = await fetch(target, init);

  // Stream the body through; keep WooCommerce pagination headers, which the
  // app needs for server-side pagination.
  const headers = new Headers({ 'content-type': 'application/json' });
  for (const name of ['x-wp-total', 'x-wp-totalpages']) {
    const value = res.headers.get(name);
    if (value) headers.set(name, value);
  }
  return new Response(res.body, { status: res.status, headers });
});

export default app;
